[workspace]
channels = ["conda-forge"]
name = "smart-microscopy-zeiss-cd7-zenblue3_9"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
start = "python main.py"

[dependencies]
numpy = ">=2.3.2,<3"
aicspylibczi = ">=3.3.1,<4"
pandas = ">=2.3.1,<3"
napari = ">=0.5.0,<0.6"
pyqt = ">=5.15.11,<6"

[pypi-dependencies]
bioio = ">=3.0.0,<4"
bioio-czi = ">=2.4.0, <3"
